apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cert-tracker.fullname" . }}-domains
  namespace: {{ include "cert-tracker.namespace" . }}
  labels:
    {{- include "cert-tracker.labels" . | nindent 4 }}
data:
  domains.json: "[{{ range $index, $domain := .Values.configMap.domains }}{{ if $index }}, {{ end }}\"{{ $domain }}\"{{ end }}]"
