apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
  namespace: {{ include "cert-tracker.namespace" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.redis.image.port }}
      targetPort: {{ .Values.redis.image.port }}
  selector:
    {{- include "redis.labels" . | nindent 4 }}
