apiVersion: v1
kind: Service
metadata:
  name: {{ include "cert-tracker.fullname" . }}
  namespace: {{ include "cert-tracker.namespace" . }}
  labels:
    {{- include "cert-tracker.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "cert-tracker.labels" . | nindent 4 }}