replicaCount: 1

namespaceOverride: ""
fullnameOverride: ""

image:
  repository: ttl.sh/7417837a-c117-4371-9b99-8da5a3f33580
  pullPolicy: IfNotPresent
  tag: "2h"
  pullSecrets: []

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"

probes:
  livenessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 1
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 1

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

redis:
  name: redis
  image:
    repository: redis
    tag: "7.4"
    port: 6379
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  schedule: "0 0 * * *"

checkjob:
  schedule: "10 0 * * *"

curl:
  repository: curlimages/curl
  tag: "7.85.0"
  imagePullPolicy: IfNotPresent

configMap:
  domains:
    - vodafone.com
    - vodafone.gr
    - vodafonecu.gr
    - google.com
    - youtube.com
    - srekubecraft.io
    - example.com

monitoring:
  namespace: monitoring

hpa:
  minReplicas: 1
  maxReplicas: 4
  cpuUtilization: 50
  memoryUtilization: 50